services:
  saida-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saida-web-app
    ports:
      - "8087:80"
    volumes:
      # Montage des données GeoJSON dans un sous-dossier distinct
      - ./public/geojson_data:/usr/share/nginx/html/data/geojson_data
    restart: unless-stopped