services:
  saida-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saida-web-app
    ports:
      - "8080:80"
    volumes:
      # Montage spécifique des données GeoJSON seulement
      - ./public/geojson_data:/usr/share/nginx/html/geojson_data
    restart: unless-stopped